import {
  ThumbnailTemplate,
  StoryTemplate,
  PlannerItem,
  UserSettings,
} from "./types";

export const DEFAULT_SETTINGS: UserSettings = {
  theme: "dark",
  fontSize: "medium",
  language: "fa",
  vipStatus: false,
  tapsellKey: "",
  cafeBazaarRsaKey: "",
  developer: "سیدحمیدموسوی زاده",
  appName: "CreatorFlow",
  customAppIcon: "/app-icon.png",
  version: "1.0.0",
  versionCode: 1,
};

export const TAPSELL_CONFIG = {
  rewardedAdId: "6aa84a381f07c00619f451f1",
  bannerAdId: "6aa84a4fcd33cd4ed6e43287",
};

export const INITIAL_THUMBNAILS: ThumbnailTemplate[] = [
  {
    id: "thumb-1",
    title: "Extreme Tech Review",
    category: "Tech",
    bgGradient: "from-slate-900 via-indigo-950 to-blue-900",
    headline: "DON'T BUY THIS!",
    subheadline: "Until You Watch This 2026 Breakdown",
    badge: "HONEST REVIEW",
    badgeColor: "bg-red-500 text-white",
    textColor: "text-yellow-400",
    accentColor: "#38BDF8",
    isVIP: false,
  },
  {
    id: "thumb-2",
    title: "Pro Gaming Highlight",
    category: "Gaming",
    bgGradient: "from-purple-950 via-fuchsia-950 to-slate-950",
    headline: "UNSTOPPABLE CLUTCH",
    subheadline: "0.01s Impossible Victory",
    badge: "RANK #1 GLOBAL",
    badgeColor: "bg-amber-500 text-black",
    textColor: "text-cyan-300",
    accentColor: "#E879F9",
    isVIP: false,
  },
  {
    id: "thumb-3",
    title: "Financial Freedom Secret",
    category: "Finance",
    bgGradient: "from-emerald-950 via-teal-950 to-slate-900",
    headline: "MY $10,000 STRATEGY",
    subheadline: "Passive Income in 30 Days",
    badge: "100% PROVEN",
    badgeColor: "bg-emerald-500 text-black",
    textColor: "text-emerald-300",
    accentColor: "#34D399",
    isVIP: true,
  },
  {
    id: "thumb-4",
    title: "Masterclass Tutorial",
    category: "Education",
    bgGradient: "from-blue-950 via-slate-900 to-indigo-950",
    headline: "LEARN IN 10 MINUTES",
    subheadline: "Zero to Hero Step-by-Step",
    badge: "BEGINNER FRIENDLY",
    badgeColor: "bg-blue-600 text-white",
    textColor: "text-white",
    accentColor: "#60A5FA",
    isVIP: false,
  },
  {
    id: "thumb-5",
    title: "Dramatic Deep Dive",
    category: "Review",
    bgGradient: "from-zinc-950 via-red-950 to-black",
    headline: "THE DARK TRUTH",
    subheadline: "What Nobody Else is Saying",
    badge: "EXPOSED",
    badgeColor: "bg-red-600 text-white",
    textColor: "text-red-400",
    accentColor: "#F87171",
    isVIP: true,
  },
  {
    id: "thumb-6",
    title: "Deep Conversations Podcast",
    category: "Podcast",
    bgGradient: "from-amber-950 via-stone-900 to-black",
    headline: "EPISODE #42",
    subheadline: "The Mindset of Multi-Millionaires",
    badge: "EXCLUSIVE INTERVIEW",
    badgeColor: "bg-amber-600 text-white",
    textColor: "text-amber-300",
    accentColor: "#FBBF24",
    isVIP: false,
  },
];

export const INITIAL_STORIES: StoryTemplate[] = [
  {
    id: "story-1",
    title: "New Video Alert Teaser",
    category: "New Video",
    bgGradient: "from-blue-900 via-indigo-950 to-slate-950",
    headline: "NEW VIDEO IS LIVE!",
    bodyText: "Link in bio! The algorithm might take this down soon, watch before it's gone.",
    stickerText: "NEW DROP 🔥",
    buttonText: "WATCH NOW",
    isVIP: false,
  },
  {
    id: "story-2",
    title: "Behind The Scenes",
    category: "Behind The Scenes",
    bgGradient: "from-fuchsia-950 via-purple-900 to-slate-950",
    headline: "14 HOURS OF EDITING...",
    bodyText: "Putting together the biggest project of the year. Who's ready for Thursday?",
    stickerText: "BTS TEASER 🎬",
    buttonText: "TAP TO SEE SNEAK PEEK",
    isVIP: false,
  },
  {
    id: "story-3",
    title: "Community Q&A Poll",
    category: "Q&A Teaser",
    bgGradient: "from-amber-950 via-orange-950 to-stone-950",
    headline: "WHAT SHOULD I REVIEW NEXT?",
    bodyText: "Drop your questions below. Answering the top 5 in tomorrow's long-form video.",
    stickerText: "Q&A TIME ❓",
    buttonText: "REPLY WITH SUGGESTION",
    isVIP: false,
  },
  {
    id: "story-4",
    title: "Creator Milestone Announcement",
    category: "Announcement",
    bgGradient: "from-emerald-950 via-teal-900 to-slate-950",
    headline: "WE HIT 100K SUBSCRIBERS!",
    bodyText: "Could not have done this without every single one of you. Special giveaway announcement inside.",
    stickerText: "THANK YOU! 🎉",
    buttonText: "JOIN THE GIVEAWAY",
    isVIP: true,
  },
];

export const INITIAL_PLANNER_ITEMS: PlannerItem[] = [
  {
    id: "plan-1",
    title: "5 AI Tools That Will Replace Your Editor in 2026",
    platform: "YouTube Long",
    stage: "Recording",
    dueDate: "2026-09-20",
    notes: "Record B-Roll of prompt engineering and screen captures",
    priority: "High",
  },
  {
    id: "plan-2",
    title: "Stop Making This Shorts Mistake (Instant 0 Views)",
    platform: "YouTube Shorts",
    stage: "Editing",
    dueDate: "2026-09-17",
    notes: "Fast 15-second loop with sound effects and captions",
    priority: "High",
  },
  {
    id: "plan-3",
    title: "Behind the Scenes Studio Tour 2026",
    platform: "YouTube Long",
    stage: "Scripting",
    dueDate: "2026-09-25",
    notes: "Show lighting setup, microphone comparison, and desk gear",
    priority: "Medium",
  },
  {
    id: "plan-4",
    title: "How I Grew 10k Subs With 0 Ad Spend",
    platform: "Multi-platform",
    stage: "Thumbnail",
    dueDate: "2026-09-19",
    notes: "Design high contrast thumbnail with graph trending upwards",
    priority: "High",
  },
  {
    id: "plan-5",
    title: "Weekly Motivation & Channel Update",
    platform: "Instagram Story",
    stage: "Ready",
    dueDate: "2026-09-16",
    notes: "3 story frames with poll sticker and link sticker",
    priority: "Low",
  },
];
